# This is a basic workflow to help you get started with Actions

name: Flatpak Builder

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ Flatpak ]
  pull_request:
    branches: [ Flatpak ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  flatpak-builder:
    name      : "Flatpak Builder"
    runs-on   : ubuntu-latest
    container :
      image   : docker.io/bilelmoussaoui/flatpak-github-actions
      options : --privileged
    steps:
    - uses : actions/checkout@v2
    - uses : bilelmoussaoui/flatpak-github-actions@v2
      with :
        bundle        : "io.github.lyaaaaaaaaaaaaaaa.Project_Kanban.flatpak"
        manifest-path : "io.github.lyaaaaaaaaaaaaaaa.Project_Kanban.yml"
        branch        : "Flatpak"
